### ISSUE TITLE
When running node.js v10, ECONNRESET happens on second and any onward message

### ISSUE THREAD

**Issue by hajekj** [substack/node-smtp-protocol#34]
I am running Windows 8.1 with node.js v10 (and v11 too). The script runs on port 25, with all the necessary TLS settings (key and cert). The first email arrives just fine, however any onward message results with following error:
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

Any idea what am I doing wrong?

This appears to be happening only when sending email using TLS.

**Comment by jmhobbs** [comment]
There is a scope issue in this fix with istls, which is related to the initial net/tls server.  If you have concurrent connections with overlapping tls sessions, you get the same error as before the proposed fix.

This version tracks the tls status inside the scope of the request, and works with overlapping client sessions.

jmhobbs/node-smtp-protocol@46057d8851ed1a04e95db722d14a5eb97730daa1

As for closing the tserver, I think that is correct, since it is opened specific to the connected client and you wouldn't want to reuse that between clients.

**Comment by hajekj** [comment]
I will try applying this patch onto my server and see if it works correctly. Thank you.

**Comment by substack** [comment]
Awaiting the results, ready to merge.

**Comment by hajekj** [comment]
I just ran couple of messages through it using TLS, non-TLS connections, everything seems to work very well and smoothly.

**Comment by substack** [comment]
Published in 2.4.6. Thanks everybody!
